version: "3.8"

services:
  app:
    build: ./docker
    image: test
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mysql:8
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql-config.cnf:/etc/mysql/conf.d/config.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

volumes:
  mysql-data:
